### ISSUE TITLE
Leaked .env file

### ISSUE THREAD

**Issue by MuchaSsak** [jayantghadge/netflix-reactJs#2]
I wanted to see the application on my local machine and start making changes, but I couldn't start it up due to lacking an API_KEY variable. There is no mention of environment files in the documentation (README.md), but more importantly I saw a commit deleting the .env file.....

You can't just upload your secrets to GitHub like that and delete them in a next commit. Those changes are visible to everyone.

I'd recommend deleting this repository altogether and create a new one without this .env file to begin with. Or if you can, change/reset all of these api keys and ids (if you haven't already)

**Comment by jayantghadge** [comment]
Thank you for bringing this to my attention. I've deleted the commit history to remove any trace of the sensitive information. Additionally, I'll review and update the repository's documentation to provide clear instructions. 

If you have any further concerns or suggestions, please feel free to let me know.

**Comment by MuchaSsak** [comment]
Alright, but keep in mind that as long as I recall properly, "deleted" commits only actually expire after 90 days or so. But as long as you know what you are doing, everything's going to be fine.
Cheers!

**Comment by jayantghadge** [comment]
I deleted commit history using git filter-repo which immediately removes a specific commit. 
Thanks again, and cheers! 🚀
